# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Kevin Dewalt on SaaS
twitter_url:       <a href="https://twitter.com/kevindewlat" target="_blank">@kevindewalt</a>.
tagline:          'Concierge onboarding and other strategies to increase MRR for SaaS founders'
headshot:         '/images/headshot.jpg'
description:      'Founder <a href="http://try.sohelpful.me" target="_blank">SoHelpful</a>. <a href="https://angel.co/kevindewalt" target="_blank">Angel investor</a>.'
sub_description:  'Here I write about SaaS products and concierge onboarding - everything I''m learning in the <a href="/sohelpfulio">sohelpful.io</a> project.'
url:              http://kevindewalt.github.io
baseurl:          /
image_url:        /images

author:
  name:           'Kevin Dewalt'
  url:            https://twitter.com/kevindewalt

paginate:         5