# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Kevin Dewalt
twitter_url:       <a href="https://twitter.com/kevindewlat" target="_blank">@kevindewalt</a>.
tagline:          'Kevin Dewalt''s blog'
headshot:         '/images/headshot.jpg'
description:      'Founder <a href="http://try.sohelpful.me" target="_blank">SoHelpful</a>, <a href="https://angel.co/kevindewalt">angel investor</a>. <br> <br> Working on <strong>sohelpful.io</strong> to help fellow SaaS founders ++conversions and --churn with <strong>concierge onboarding</strong>. '
url:              http://kevindewalt.github.io
baseurl:          /

author:
  name:           'Kevin Dewalt'
  url:            https://twitter.com/kevindewalt

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           http://kevindewalt.github.io
